#NETWORKS

networks:
  inception_network:
    name: inception
    driver: bridge

#SERVICES

services:

  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: ./.env
    networks: inception
    volumes: mariadb_data:/var/lib/mysql
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    depends_on: wordpress
    ports: "443:443"
    networks: inception
    volumes: -nginx_wordpress_data:/var/www/html
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on: -mariadb
    env_file: ./.env
    networks: inception
    volumes: nginx_wordpress_data:/var/www/html
    restart: always

#VOLUMES

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      device: /home/stopp/data/mariadb
      o: bind
      type: none
  nginx_wordpress_data:
    driver: local
    driver_opts:
      device: /home/stopp/data/wordpress
      o: bind
      type: none
